# -*- coding: utf-8 -*-
"""
/***************************************************************************
 XGeoAIPollutionAnalyst
                                 A QGIS plugin
 Explainable, Geospatial, Artificial Intelligence-Driven Analysis for Pollution Data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-25
        copyright            : (C) 2024 by Msc Student at Politecnico di Milano (POLIMI)
        email                : nshwan.khairalla@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load XGeoAIPollutionAnalyst class from file XGeoAIPollutionAnalyst.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .XGeoAI_Pollution_Analyst import XGeoAIPollutionAnalyst
    return XGeoAIPollutionAnalyst(iface)
